name: OLX Bot Scraper

on:
  schedule:
    - cron: '*/30 * * * *'  # Запуск що 30 хвилин
  workflow_dispatch: false # Дозволяє запускати вручну

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v3

      - name: Встановлення Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Встановлення Puppeteer
        run: npm install

      - name: Запуск бота
        run: node main.js
